### ISSUE TITLE
nested structure decode

### ISSUE THREAD

**Issue by tyranno** [zet23t/cpp-struct-js#1]
Hi,

The nested struct did not decoded with {endian: LE}.

**[[workaround]]**

struct.type = function(type,size,count) {
	if (type.size && count === undefined) {
		count = size;
		size = type.size();
	}
	return new struct(type.name || type, [], count, size)
		.setEncoder(
			(buffer,pos,data,opt)=>{
				type.encode(buffer,pos,data,opt)
			}
		)
		.setDecoder(
			**// (buffer,pos,data,opt)=>{
			// 	return type.decode(buffer,pos,opt);
			// }**
			(buffer,pos,opt)=>{
				return type.decode(buffer,pos,opt);
			}
		)
}

**Comment by jwmsg0525** [comment]
I was troubled by the same issue.
thanks to this comment, I solved it. I hope it will be reflected soon.

**Comment by zet23t** [comment]
Thank you for the report. I checked, added a test, confirmed and patched the code according to your suggestion.
Sorry that I didn't see the notification about this issue last year and that this caused trouble - I honestly didn't think this package was used by anyone...

**Comment by jwmsg0525** [comment]
when i can use latest patch from npm?

**Comment by zet23t** [comment]
Excuse my unfamiliarity with npm - I published now a new version (1.0.2) with the update.
